# Generated by Django 3.2.9 on 2022-04-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220414_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
