# Generated by Django 3.2.9 on 2022-04-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220415_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landing',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='landing',
            old_name='title_ua',
            new_name='title_uk',
        ),
    ]
