# Generated by Django 3.2.9 on 2022-04-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220415_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landing',
            old_name='description_en',
            new_name='description_en_us',
        ),
        migrations.RenameField(
            model_name='landing',
            old_name='title_en',
            new_name='title_en_us',
        ),
    ]
