# Generated by Django 3.2.9 on 2022-04-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220415_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landing',
            name='title_en_us',
        ),
        migrations.AddField(
            model_name='landing',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
