# Generated by Django 3.2.9 on 2022-04-26 12:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220420_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landing',
            name='image',
        ),
        migrations.AlterField(
            model_name='landing',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='description_uk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='title_en',
            field=ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='title_uk',
            field=ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
