# Generated by Django 3.2.9 on 2022-05-02 15:42

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=255, verbose_name='Заголовок')),
                ('title_uk', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description_meta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание мета')),
                ('keywords_meta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords мета')),
                ('page_title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('page_title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('page_title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Тело поста')),
                ('description_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Тело поста')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Тело поста')),
                ('created', models.DateField(verbose_name='Создан')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Превью')),
                ('image_uk', models.ImageField(null=True, upload_to='news/', verbose_name='Превью')),
                ('image_en', models.ImageField(null=True, upload_to='news/', verbose_name='Превью')),
                ('viewed', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Просмотрено')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
