# Generated by Django 3.2.9 on 2022-05-03 18:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220502_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_meta_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание мета'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_meta_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание мета'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords_meta_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords мета'),
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords_meta_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords мета'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_en',
            field=ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_uk',
            field=ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
