# Generated by Django 3.2.9 on 2022-05-02 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default=datetime.datetime(2022, 5, 2, 18, 13, 41, 536751, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
