# Generated by Django 3.2.9 on 2022-04-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_en',
            field=models.ImageField(null=True, upload_to='news/', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_uk',
            field=models.ImageField(null=True, upload_to='news/', verbose_name='Превью'),
        ),
    ]
