# Generated by Django 3.2.9 on 2022-05-08 11:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220506_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
    ]
