# Generated by Django 3.2.9 on 2022-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220426_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='viewed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Просмотрено'),
        ),
    ]
