# Generated by Django 3.2.9 on 2022-04-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(verbose_name='Создан'),
        ),
    ]
