# Generated by Django 3.2.9 on 2022-05-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20220502_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='viewed',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Просмотрено'),
        ),
    ]
