# Generated by Django 3.2.9 on 2022-05-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20220502_1307'),
        ('news', '0013_auto_20220502_1329'),
    ]

    operations = [
    ]
