# Generated by Django 3.2.9 on 2022-05-02 13:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Тело поста'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Тело поста'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_uk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Тело поста'),
        ),
    ]
