# Generated by Django 3.2.9 on 2022-05-02 13:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20220502_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='asd',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
