# Generated by Django 3.2.9 on 2022-05-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20220502_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_uk',
        ),
    ]
