# Generated by Django 3.2.9 on 2022-05-02 13:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20220502_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Тело поста'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Тело поста'),
        ),
    ]
